# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: GKP-AgentPool-Self

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'
  displayName: 'Install .NET SDK'

- script: dotnet restore src/productservice/productservice.csproj
  displayName: 'Restore'

- script: dotnet build src/productservice/productservice.csproj --no-restore
  displayName: 'Build'

- script: dotnet test test/MyNUnitTests/MyNUnitTests.csproj
  displayName: 'Test'

- script: dotnet publish src/productservice/productservice.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyServiceConnection'
    appType: 'webApp'
    appName: 'DevopsAPIServiceCICD'
    package: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Deploy to Azure Web App'
